### ISSUE TITLE
[Feature]: F# kernel 

### ISSUE THREAD

**Issue by anpin** [tweag/jupyenv#393]
### What's missing?

Would be great to have [IfSharp](https://github.com/fsprojects/IfSharp) or [ dotnet interactive](https://github.com/dotnet/interactive) kernel included in this repo, so one could run `F# ` notebooks

**Comment by ShalokShalom** [comment]
Considering that IfSharp being obsolete and that dotnet interactive does support Javascript, C#, F#, SQL and many others and them being used polyglot, I think it's time to rename this issue and focus straight on dotnet interactive. 

https://github.com/dotnet/interactive

**Comment by anpin** [comment]
opened PR which adds dotnet-interactive kernel for C# and F#
