### ISSUE TITLE
Community/Discord?

### ISSUE THREAD

**Issue by volkswagenfeature** [tweag/jupyenv#396]
Hey, I was wondering if you guys have a mailing list/discord/community somewhere. I'm starting a project where I'm trying to package [magma-nvim](https://github.com/dccsillag/magma-nvim) for nix. To that end I was hoping to rely heavily on the work you guys have done on the jupyter kernels and I'm probably going to have a bunch of basic questions about functionality and just about your codebase in general, and was wondering if there's a better way to contact you guys than clogging your issues page?

**Comment by djacu** [comment]
@volkswagenfeature See https://jupyenv.io/community/get-involved/
