### ISSUE TITLE
[Bug/Question]: Unsure how to correctly pass in a different nixpkgs commit to iHaskell

### ISSUE THREAD

**Issue by MMesch** [tweag/jupyenv#446]
### Current Behavior

I am trying to build this configuration which uses the `haskellPackages.Frames`. It fails to build with Frame dependency `htoml` marked as broken. I tried to find a commit that works and indeed there is one. `nix build github:nixos/nixpkgs/710fed5a2483f945b14f4a
58af2cd3676b42d8c8#haskellPackages.htoml` and `nix build github:nixos/nixpkgs/710fed5a2483f945b14f4a
58af2cd3676b42d8c8#haskellPackages.Frames` both work. However, when adding this to the `flake.nix`, the package is still broken. Any idea why? I suspect that there are different parallel nixpkgs commits at play but unsure.

https://gist.github.com/MMesch/8b0f9340e58c4484dfafe29521a2a9db

### Expected Behavior

I would expect the Kernel to use `inputs.nixpkgs` to build its packages.

### Steps To Reproduce

```
git clone https://gist.github.com/8b0f9340e58c4484dfafe29521a2a9db
cd 8b0f9340e58c4484dfafe29521a2a9db
nix run
```

### OS

```shell
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.85, NixOS, 22.05 (Quokka), 22.05.4690.08741686397`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(matto): `"home-manager-22.05.tar.gz, nixos-22.05, unstable"`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Version

It's in the linked Gist

**Comment by GTrunSec** [comment]
> sets the nixpkgs by each kernel args or through global config.nixpkgs, which one is better?

On the other hand, that makes the interface pretty easy for users to pass a different version of nixpkgs to a kernel.

**Comment by MMesch** [comment]
Thanks @GTrunSec that's helpful and it makes sense having the possibility to pass separate nixpkgs to each kernel. But how do you pass nixpkgs through exactly? I am not that familiar with the module system and am confused. The little snippet that you wrote above doesn't work in itself because it complains that nixpkgs isn't defined where the Haskell kernel is defined.

**Comment by MMesch** [comment]
This works. I have an alternative one-file config here if anyone is interested: https://gist.github.com/MMesch/16fb1c2f80c775fb75af5618f945c1d4
