### ISSUE TITLE
Question: how to provide nex cargo hashes for python packages with rust dependencies?

### ISSUE THREAD

**Issue by jaapterwoerds** [tweag/jupyenv#468]
I want to provide an overrides along the lines of this but it requires access to additional argument other than final and prev. Unfortunately, because the overrides attribute is a file instead of function I don't have a straightforward way to use the pkgs provided in the kernels module? 
``` overrides.nix
final: prev: {
  cryptography =
    let getCargoHash = version: {

            "40.0.1-vendor" = "sha256-gFfDTc2QWBWHBCycVH1dYlCsWQMVcRZfOBIau+njtDU=";


          }.${version} or (
          #How?
            lib.warn "Unknown cryptography version: '${version}'. Please update getCargoHash." builtins.lib.fakeHash
          );
          in
            prev.cryptography.overridePythonAttrs(old: {
                #How?
               cargoDeps =  pkgs.rustPlatgorm.fetchCargoTarball {
                 inherit (old) src;
                 name = "${old.pname}-${old.version}";
                 hash = getCargoHash old.version;
              };
         });

}
```

**Comment by GTrunSec** [comment]
Example here: https://github.com/tweag/jupyenv/pull/452/commits/be03f363f46c3a0ad031aa0c90b130a9b3fc8616#diff-cfc9255ab96fac9007f71aac899e2e98bccdb7889d63beadf258c450670477cbR17

**Comment by jaapterwoerds** [comment]
Thanks for your pointer. I must have searched only for 'getCargoHash' and tried a few things that were not prev.pkgs.xxx . Let's say it was a long day
