### ISSUE TITLE
[Feature]: Add an interface for specifying native build inputs in a kernel. 

### ISSUE THREAD

**Issue by ILikePizza555** [tweag/jupyenv#497]
### What's missing?

Related to #442

I'm requesting this because I ran into a similar issue when trying to install `reacton` as part of my kernel. It fails to build for similar reasons as `pathspec` -- it uses `hatchling` as it's build backend and this results in `poetry` not adding the package to the flake.lock.

In the linked issue, it was stated that the override solution would be included as part of jupyenv. However, I think that in addition to that, jupyenv should expose an interface for specifying additional `nativeBuildInputs`.

For example, a `nativeBuildInputs` which would go inside `kernels.nix` that would be an attrset of functions that take `pythonPackages` and return a list of packages.

**Comment by GTrunSec** [comment]
see https://github.com/tweag/jupyenv/pull/524/commits/48decf0efce2208487a7db06e987a8dffc74c146
